Fix build on gcc-13: add missing <stdint.h> include
[ 15%] Building CXX object src/CMakeFiles/kcov.dir/writers/cobertura-writer.cc.o
In file included from kcov/src/writers/cobertura-writer.cc:6:
kcov/src/include/reporter.hh:24:90: error: 'uint64_t' has not been declared
   24 |      LineExecutionCount(unsigned int hits, unsigned int possibleHits, uint64_t order) :
      |                                                                       ^~~~~~~~